Document: gestioip
Title: Debian gestioip Manual
Author: <insert document author here>
Abstract: This manual describes what gestioip is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gestioip/gestioip.sgml.gz

Format: postscript
Files: /usr/share/doc/gestioip/gestioip.ps.gz

Format: text
Files: /usr/share/doc/gestioip/gestioip.text.gz

Format: HTML
Index: /usr/share/doc/gestioip/html/index.html
Files: /usr/share/doc/gestioip/html/*.html
